stages:
  prepare-data-d2v:
    cmd: python src/get_data.py --model d2v
    deps:
      - /home/azagar/myfiles/t5/data/asn-summary-plus-sta-lead
      - /home/azagar/myfiles/metamodel/data/surs.jsonl
    outs:
      - /home/azagar/myfiles/metamodel/data/doc2vec-training.jsonl

  prepare-data-metamodel:
    cmd: python src/get_data.py --model metamodel
    deps:
      - /home/azagar/myfiles/t5/data/asn-summary-plus-sta-lead
      - /home/azagar/myfiles/metamodel/data/surs.jsonl
    outs:
      - /home/azagar/myfiles/metamodel/data/metamodel-training.jsonl
