stages:
  prepare-data-d2v:
    cmd: python src/get_data.py --model d2v
    deps:
      - /home/azagar/myfiles/kas_final/final/kas.corpus/kas.txt
      - /home/azagar/myfiles/t5/data/asn-summary-plus-sta-lead
      - /home/azagar/myfiles/metamodel/data/surs.jsonl
    outs:
      - /home/azagar/myfiles/data/doc2vec-training.jsonl

  prepare-data-metamodel:
    cmd: python src/get_data.py --model metamodel
    deps:
      - /home/azagar/myfiles/kas_final/final/kas.abstracts
      - /home/azagar/myfiles/kas_final/final/kas.corpus/kas.txt
      - /home/azagar/myfiles/t5/data/asn-summary-plus-sta-lead
      - /home/azagar/myfiles/metamodel/data/surs.jsonl
    outs:
      - /home/azagar/myfiles/data/metamodel-training.jsonl
